name: nf-virontus-2.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::bcftools=1.10.2
  - bioconda::ivar=1.3.1
  - bioconda::kraken2=2.1.1
  - bioconda::longshot
  - bioconda::minimap2=2.17
  - bioconda::multiqc=1.9
  - bioconda::pbgzip
  - bioconda::samtools
  - bioconda::snpeff=5.0
  - bioconda::snpsift=4.3.1t
  - conda-forge::pigz
  - conda-forge::python>=3.6
  - conda-forge::wheel
  - conda-forge::cxx-compiler
  - pip
  - pip:
    - attrs
    - biopython
    - click>=7.0
    - jedi
    - medaka==1.2.5
    - numpy
    - odfpy
    - pandas
    - rich>=9.8.1
    - seaborn
    - typer>=0.3.2
    - xlrd
