name: nf-virontus-1.1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9
  - centrifuge=1.0.4_beta
  - flye=2.6
  - ivar=1.2.2
  - kraken2=2.0.8_beta
  - minimap2=2.17
  - samtools=1.9
  - medaka=0.12.1
  - longshot
  - seqtk=1.3
  - pbgzip
  - unicycler=0.4.7
  - python=3.6.7
  - pip=19.3.1
  - pip:
    - attrs==19.3.0
    - biopython==1.76
    - click==7.0
    - filter_classified_reads==0.2.0
    - vcf_consensus_builder
    - numpy==1.18.0
    - pandas==0.25.3
    - seaborn